apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-deployment
spec:
  params:
    - name: deployment
      description: The name of the deployment to patch with the new image
      type: string
    - name: IMAGE
      description: The full location of the new image to be used
      type: string
  steps:
    - name: check-deployment
      image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
      script: |
        set -e
        # Check if the deployment exists
        if ! oc get deployment $(params.deployment); then
          echo "Error: Deployment $(params.deployment) not found."
          exit 1
        fi
    - name: update-image
      image: image-registry.openshift-image-registry.svc:5000/openshift/cli:latest
      script: |
        set -e
        # Patch the deployment to update the image
        oc patch deployment $(params.deployment) --type='json' -p='[
          {
            "op": "replace",
            "path": "/spec/template/spec/containers/0/image",
            "value": "$(params.IMAGE)"
          }
        ]'
