apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-app-deployment
  labels:
    app: php-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: php-app
  template:
    metadata:
      labels:
        app: php-app
    spec:
      containers:
      - name: php-app
        image: image-registry.openshift-image-registry.svc:5000/demo1-mtp/app-juego-ui
        ports:
        - containerPort: 80
        args: ["/bin/sh", "-c", "chmod 666 /etc/apache2/apache2.conf && echo 'ServerName localhost' >> /etc/apache2/apache2.conf && chmod 644 /etc/apache2/apache2.conf && apache2-foreground"]
        volumeMounts:
        - name: php-app-storage
          mountPath: /var/www/html
      volumes:
      - name: php-app-storage
        persistentVolumeClaim:
          claimName: php-app-pvc
