apiVersion: v1
kind: Service
metadata:
  name: php-app-service
  labels:
    app: mysql
spec:
  selector:
    app: php-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
